language: csharp

dotnet: 1.0.4
mono: none
dist: trusty

script: ".travis/build.sh"

before_deploy: ".travis/deploy.sh"

deploy:
  provider: releases
  api_key:
    secure: gXmExaOYIHmDPxFR0Dt0y3hRDKrBpKRHy+RXcnbpjG0Zl+OfSOmwNIQiSFywrbPCnIAaAd8QoAGq8ogPz9H3UedDznhm27G3KVOoGUYesGDki8Tqpe0bl0hocOcPXuBZuXmckw2Xb0/W2CaWW1Tuo9N95+M2Ior1pVGqQFyvPpDafNDzJ/V1agwv/N31NvaIuxdaPkD5NC3qPM9WBkiZOJGufYmdG6y5ud9EmPMa8sOXorhT+5pTz1MwduUtu+lepswDfkuJ4r5dFl9Fxbvvu+VORv0VSS8ucOitfHzsfc6GdbHairniyXHhV+WrNW2Fu03zm6Rqel2eMs2vaIe9mLtUtW4HHbJuHCVx+n0J21i5AYBo7M5srzSx7XKdbR5IH0CgceYwESOR1edjfL5Ie/wv+RMPkonSlA2yICLbAgRY+kCZSt2FeePduuYXeEZd+pJNcJikQN6/vtxQOsHVIs/oezkVp8B5GVTGjBd4Be3KdYLlC0IR4+wBTEqYXrj8UcMcVPUzbsqbd++XTQBhxB1j2QagkeD3A+fXDFUP2x45MZSFsXCMqmK/3XHQeoVVRhwnsPU6psJ6c/5ISBVAo6HIwxLSDWa9ys+Hi9Cr1oKLugkKePCCQzpDlbDjC7FVTMKl7pQ5EU8kba1L88LbbHHaQx8fdt9EOPHi4TEP7Xg=
  file_glob: true
  file: EveClientDownloader.*.nupkg
  skip_cleanup: true
  on:
    repo: Eve-Utils/EveClientDownloader
    branch: master
    tags: true
