language: csharp

dotnet: 1.0.4
mono: none
dist: trusty

script: chmod +x .travis/build.sh && .travis/build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x .travis/deploy.sh && .travis/deploy.sh
  on:
    branch: master
    tags: true
